lab1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#

movies/urls.py
from django.urls import path
from . import views

app_name = "movies"
urlpatterns = [
    # there will probably be namespace collision with the index name we'll see about that later
    # name spacing solves this issue as you can see app_name over ther and {% url 'movies:index' %}
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('add', views.add_movie, name="add")
]

movies/models.py
from django.db import models
import uuid

# Create your models here.
class Movie(models.Model):
    # django auto creates id field could have saved myself hours 😢 of reading
    # movie_id = models.UUIDField( primary_key = True, default = uuid.uuid4, editable = False)
    name = models.CharField(max_length=250, blank=False, null=False)
    discription = models.TextField(null=True, blank=True)
    release_date = models.DateField(null=True, blank=True)
    budget = models.IntegerField(null=True, blank=True, default=0)
    cast = models.ForeignKey("Cast", related_name="movies", on_delete=models.DO_NOTHING, null=True, blank=True)
    poster = models.ImageField( upload_to='')
    def __str__(self):
        return self.name
    
    # 
class Category(models.Model):
    movies = models.ManyToManyField("Movie",related_name="category",null=True, blank=True)
    # categor_id = models.AutoField()
    name = models.CharField(max_length=40, null=False, blank=False)
    description = models.CharField(max_length=1000, null=True, blank=True)


    def __str__(self):
        return self.name



class Leader(models.Model):
    name = models.CharField(max_length=120, null=False, blank=False)
    def __str__(self):
        return self.name


class Cast(models.Model):
    number_of_people = models.IntegerField()
    leader = models.OneToOneField('Leader', on_delete=models.CASCADE, related_name="cast", null=True, blank=True)

    def __str__(self):
        return f'{self.leader.name}\'s Cast'

movies/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .form import MovieForm
from .models import Movie
from django.contrib.auth.decorators import login_required

# we will get this from the database 
movie_list = []
# Create your views here.
@login_required
def index(request):
    # return HttpResponse('hello fuckface')
    return render(request, 'movies/index.html', context={ 'movie_list': Movie.objects.all()} )
# 
def add_movie(request):
    if request.method == 'GET':
        return render(request, 'movies/movie_add.html', context={ 'form': MovieForm() })
    elif request.method == "POST":
        form = MovieForm(data=request.POST, files=request.FILES, instance=Movie)
        if form.is_valid():
            # name = form.cleaned_data['name']
            # print(form.cleaned_data)
            print(form.cleaned_data)
            # m = Movie(**form.cleaned_data)
            # m.save()
            form.save()
            return redirect('movies:index')
        else:
            return render(request, 'movies/movie_add.html', context={ 'form': form })

def home(request):
    return render(request, 'base.html')

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block title %}Movies{% endblock title %}Movies
{% block content %}
<table class="table table-striped">
<tr>
<th scope="table" >poster</th>
<th scope="table" >name</th>
<th scope="table" >description</th>
<th scope="table" >release date</th>
<th scope="table" >budget</th>
<ta>
{% comment %}  {% endcomment %}
{% for movie in movie_list  %}
<tr>
    
 <td><img src="{{ movie.poster }}"></td>
 <td>{{ movie.name }}</td>
 <td>{{ movie.discription  }}</td>
 <td>{{ movie.release_date }}</td>
 <td>{{ movie.budget }}</td>
</tr>
{% empty %}
no movies sorry
{% endfor %}
</table>

<a type="button" class="btn btn-warning" href={% url "movies:add"%}>+ add</a>
{% endblock %}

movies/templates/movies/movie_add.html
{% extends 'base.html' %}


{% block content%}
    {% load crispy_forms_tags %}  
    <form action="" method="POST" class=".m-sm-auto">
    {% csrf_token %}
    {{form | crispy}}
    <input type="submit" value="submit" class="btn btn-warning mt-3">
    </form>
    
{% endblock %}