lab1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#

movies/urls.py
from django.urls import path
from . import views

app_name = "movies"
urlpatterns = [
    # there will probably be namespace collision with the index name we'll see about that later
    # name spacing solves this issue as you can see app_name over ther and {% url 'movies:index' %}
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('add', views.add_movie, name="add")
]

todo/urls.py
from django.urls import path
from . import views

# app_name in urls.py is the name spacing and you'll have to add a colon APP_NAME: before route in views.py redirect and in template url
app_name = "todo"

urlpatterns = [
    path('tasks/', views.index , name='index'),
    # this seems like a better way to create at tasks/add instead of tasks/. but i don't know for sure 
    path('tasks/add/', views.create_task, name='create_task'),
    path('tasks/<int:task_id>/', views.tasks, name='view_task'),
    path('tasks/<int:task_id>/update/', views.update_task, name='update_task'),
    # path('tasks/<int:task_id>/delete', views.delete_task, name='delete_task'),
    # why did i do this to myself again
]

todo/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from random import random


my_task_list = [
    {
        'index': 0,
        'id': 1,
        'name': 'Movie-1',
        'priority': 1,
        'description': "hello iam studying at iti sahdjka shkdj sahjkfghdadsgfadfadsgasdfasfffffffffffffhsadjksahdjkashkdjsahjkfghdadsgfadfadsgasdfasfffffffffffffhsadjksahdjkashkdjsahjkfghdadsgfadfadsgasdfasfffffffffffffhsadjksahdjkashkdjsahjkfghdadsgfadfadsgasdfasfffffffffffff",
    },
    {
        'index': 1,
        'id': 2,
        'name': 'Movie-2',
        'priority': 4,
        'description': "hello iam studying at iti sahdjka shkdj sahjkfghdadsgfadfadsgasdfasfffffffffffffhsadjksahdjkashkdjsahjkfghdadsgfadfadsgasdfasfffffffffffffhsadjksahdjkashkdjsahjkfghdadsgfadfadsgasdfasfffffffffffffhsadjksahdjkashkdjsahjkfghdadsgfadfadsgasdfasfffffffffffff",
    },
    {
        'index': 2,
        'id': 3,
        'name': 'Movie-3',
        'priority': 2,
        'description': "hello iam studying at iti sahdjka shkdj ",
    },
    {
        'index': 2,
        'id': 4,
        'name': 'Movie-3',
        'priority': 2,
        'description': "hello iam studying at iti sahdjka shkdj ",
    },
    {
        'index': 2,
        'id': 5,
        'name': 'Movie-5',
        'priority': 2,
        'description': "hello iam studying at iti sahdjka shkdj ",
    },
    {
        'index': 2,
        'id': 6,
        'name': 'Movie-3',
        'priority': 2,
        'description': "hello iam ",
    },
]

def _get_target_task(target_id):
    # Filter the list based on the task id sent and compare it toward each dictionary item in the list
    filter_result = filter(lambda d: d.get('id') == target_id, my_task_list)
    final_list = list(filter_result)
    # Getting index of the required task from my_task_list
    if len(final_list) == 0:
        return -1
    else:
        index_of_task = my_task_list.index(final_list[0])
        return index_of_task

# Create your views here.
def index(request):

    return render(request, 'todo/task_list.html', context={"my_task_list": my_task_list})

def create_task_dict(p):
    return  {
    'index': p.get('index') or len(my_task_list),
    'id':  int(p.get('id') or random()*10000),
    'name': p.get('task_name'),
    'priority': p.get('priority'),
    'description': p.get('description')
    }

def tasks(request, **kwargs):
    # kwargs have task id
    t = _get_target_task(kwargs.get('task_id'))
    if t == -1:
        return HttpResponse("404 man, there is no task with that id")
    # create in task/id doesn't make anysense
    if request.method == 'POST':
        p = request.POST
        if p.get('op') == 'DELETE':

            my_task_list.pop(t)
            return redirect('todo:index')

        elif p.get('op') == 'UPDATE':
            print("\n\n------it wants to update------\n\n")
            print(p)
            # be careful of unpacking request.post it's not a simple dectianory     
            updated_task = create_task_dict(p)
            print(updated_task)
            my_task_list[t] = updated_task
            return redirect('todo:index')
    elif request.method == 'GET':
        return render(request, 'todo/task.html', context=my_task_list[t])

    # return render(request, 'task.html', context={
    #     'index': 2,
    #     'id': 3,
    #     'name': 'Movie-3',
    #     'priority': 2,
    #     'description': "hello iam studying at iti sahdjka shkdj sahjkfghdadsgfadfadsgasdfasfffffffffffffhsadjksahdjkashkdjsahjkfghdadsgfadfadsgasdfasfffffffffffffhsadjksahdjkashkdjsahjkfghdadsgfadfadsgasdfasfffffffffffffhsadjksahdjkashkdjsahjkfghdadsgfadfadsgasdfasfffffffffffff",
    # })

def create_task(request):
    if request.method == 'POST':
        p = request.POST
        new_task = create_task_dict(p)
        my_task_list.append(new_task)
        return redirect('todo:index')
    elif request.method == 'GET':
        return render(request, 'todo/task_create.html')
    
def update_task(request, **kwargs):
    t = _get_target_task(kwargs.get('task_id'))
    if t == -1:
        return HttpResponse("404 man, there is no task with that id")
    return render(request, 'todo/task_update.html', context=my_task_list[t])

todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}todo{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> {% endcomment %}
</head>
<body>


    {% block content %}{% endblock %}

</body>
</html>

todo/templates/todo/task.html
{% extends 'todo/base.html' %}

{% block title%}task{% endblock %}

{% block content %}
    <h1>task</h1>
    <h1>id:{{ id }}</h1>
    <h2>name: {{ name }}</h2>
    <h3>priority: {{priority}}</h3>
    <p>description:{{ description }}</p>

    <a href="{% url 'todo:index' %}">return to task list</a>
{% endblock content %}

todo/templates/todo/task_create.html
{% extends 'todo/base.html' %}
{% block title %}add task{% endblock title %}
{% block content %}
    <form id="form" method="POST" class="row container mx-auto w-50" action="{% block form_url %}{% url 'todo:create_task' %}{% endblock form_url %}">
        {% csrf_token %}        
        <h2>Add Task</h2>
        <input class=" form-control m-2" type="text" name="task_name" id="inpttxt" placeholder="Task Name"  value="{% block task_name %}{% endblock  %}">
        <input class=" form-control m-2" type="text" name="description" id="nameInpt" placeholder="Task Description" value="{% block description %}{% endblock  %}">
        <input class=" form-control m-2" type="text" name="priority" id="prInpt" placeholder="Task priority" value="{% block priority %}{% endblock  %}">
        {% block content2 %}{% endblock content2 %}
        <button type="submit" class="btn btn-success w-25 mx-auto">submit</button>
    </form>
{% endblock content %}

todo/templates/todo/task_list.html
{% extends "todo/base.html" %}


{% comment %}  {% endcomment %}
{% block content %}
<h1 class="text-center">Task List</h1>
<a href="{% url 'movies:home' %}" class="btn btn-secondary pill">« go home</a>
    <ul>
        {% for task in my_task_list%}
            <li class="m-3">
                id:{{task.id}} name:{{task.name}}
                <div class="btn-group" role="group">
                    <a type="button" class="btn btn-primary" href="{% url 'todo:view_task' task.id %}">view</a>
                    <label type="button" class="btn btn-secondary" for="submit_update_{{task.id}}" >update</label>
                    <label type="button" class="btn btn-danger" for="submit_delete_{{task.id}}">delete</label>
                </div>
                {% comment %} it's a form method delete hack and checkbox hack {% endcomment %}
                {% comment %} this so the delete button makes a post request with op(operation):delete to task/{{id}} {% endcomment %}
                <form action="{% url 'todo:view_task' task.id %}" method="POST" style="display: none">
                {% csrf_token %}
                <input type="text" name="op" value="DELETE">
                <input type="submit" id="submit_delete_{{task.id}}">
                </form>
                <form action="{% url 'todo:update_task' task.id %}" method="GET" style="display: none">
                {% csrf_token %}
                <input type="text" name="op" value="UPDATE">
                <input type="submit" id="submit_update_{{task.id}}">
                </form>
            </li>    
        {% endfor %}
    </ul>
<a href="{% url 'todo:create_task' %}" class="btn btn-warning">
<span class="h5">+</span> add task</a>

{% endblock content %}

todo/templates/todo/task_update.html
{% extends 'todo/task_create.html' %}

{% block form_url %}{% url 'todo:view_task' id %}{% endblock form_url %}
{% block task_name %}{{ name }}{% endblock  %}
{% block description %}{{ description }}{% endblock  %}
{% block priority %}{{ priority }}{% endblock  %}
{% block content2 %}
    <input type="text" name="op" value="UPDATE" hidden>
    <input type="text" name="index" value="{{ index }}" hidden>
    <input type="text" name="id" value="{{ id }}" hidden>
{% endblock content2 %}