accounts/urls.py
from django.urls import path, include
from accounts import views
app_name="accounts"
urlpatterns = [
    # path('logout', views.logout, name="logout"),  
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name='logout'),
    # path('', include('django.contrib.auth.urls')),
    path('', views.index, name='index'),
    path('profile/', views.index, name='profile'),
    path('signup/', views.signup, name="signup")
]

lab1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#

movies/urls.py
from django.urls import path
from . import views

app_name = "movies"
urlpatterns = [
    # there will probably be namespace collision with the index name we'll see about that later
    # name spacing solves this issue as you can see app_name over ther and {% url 'movies:index' %}
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('add', views.add_movie, name="add")
]

todo/urls.py
from django.urls import path
from . import views

# app_name in urls.py is the name spacing and you'll have to add a colon APP_NAME: before route in views.py redirect and in template url
app_name = "todo"

urlpatterns = [
    path('tasks/', views.index , name='index'),
    # this seems like a better way to create at tasks/add instead of tasks/. but i don't know for sure 
    path('tasks/add/', views.create_task, name='create_task'),
    path('tasks/<int:task_id>/', views.tasks, name='view_task'),
    path('tasks/<int:task_id>/update/', views.update_task, name='update_task'),
    # path('tasks/<int:task_id>/delete', views.delete_task, name='delete_task'),
    # why did i do this to myself again
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}todo{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static '/movies/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'movies:home' %}">Kata</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse show" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link" href="{% url 'accounts:profile' %}">Home</a>
        <a class="nav-link" href="{% url 'todo:index' %}">Todo</a>
        <a class="nav-link" href="{% url 'movies:index' %}">Movies</a>
        {% comment %} {% if request.user %}{% endif %} {% endcomment %}
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'accounts:logout'%}" >LOGOUT</a>
        {% else %}
        <a class="nav-link" href="{% url 'accounts:login' %}" >login</a>
        {% endif%}
      </div>
    </div>
  </div>
</nav>
    <div class="container">
    {% block content %}
  <div class="main-content">
    <div class="container mt-7">
      <!-- Table -->
      <h2 class="mb-5">Welcome to my demo website</h2>
      <div class="row">
        <div class="col-xl-8 m-auto order-xl-2 mb-5 mb-xl-0">
          <div class="card card-profile shadow">
            <div class="row justify-content-center">
              <div class="col-lg-3 order-lg-2">
                <div class="card-profile-image">
                  <a href="#">
                    <img src="https://raw.githubusercontent.com/kataya1/Resume/master/assits/smilyblackandwhite.jpg" style="width: 20%; ;"class="rounded-circle h-20 position-absolute top-0 start-50 translate-middle">
                    <div style="height: 15vh;"> </div>
                  </a>
                </div>
              </div>
            </div>

            <div class="card-body pt-0 pt-md-4">
              <div class="row">
                <div class="col">
    
                </div>
              </div>
              <div class="text-center">
                <h3>
                  Mo Kataya<span class="font-weight-light">, 25</span>
                </h3>
                <div class="h5 font-weight-300">
                  <i class="ni location_pin mr-2"></i>
                </div>
                <div class="h5 mt-4">
                  <i class="ni business_briefcase-24 mr-2"></i>Computer Engineer
                </div>
                <div>
                  <i class="ni education_hat mr-2"></i>Alex uni
                </div>
                <hr class="my-4">
                <p>I'v seen better days</p>
                <a href="#" target="_blank">Show more</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    
    {% endblock %}
    </div>
</body>
</html>